# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: doto-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Get Yarn Cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules for Yarn
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/doto-backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn--

      - name: Yarn Install
        working-directory: ./doto-backend
        run: yarn install --frozen-lockfile

      - name: Yarn Tests
        working-directory: ./doto-backend
        run: CI=true yarn test --passWithNoTests

  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn Cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules for Yarn
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/doto-frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn--

      - name: Yarn Install
        working-directory: ./doto-frontend
        run: yarn install --frozen-lockfile

      - name: Yarn Tests
        working-directory: ./doto-frontend
        run: CI=true yarn test --passWithNoTests

      - name: Yarn Build
        working-directory: ./doto-frontend
        run: yarn build
